### ISSUE TITLE
`name` should only be required for published packages

### ISSUE THREAD

**Issue by gerardroche** [bower/spec#22]
`name` should only be required for published packages. 

In example, both [composer](https://getcomposer.org/doc/04-schema.md) and [npm](https://www.npmjs.org/doc/files/package.json.html) only require a name for published packages.

See also _version attribute should always be required_ #4

**Comment by stevemao** [comment]
> name should only be required if private is false or not present

:+1:

**Comment by stevemao** [comment]
It should be aligned with npm

**Comment by stevemao** [comment]
Only name and version are required fields in package.json but it won't throw an error if they are missing when installing deps. So I think we should make name required here but don't throw an error if people just wanna install any deps.

**Comment by JoshMcCullough** [comment]
Agreed that `name` should be 100% optional for bower config. As pointed out in #160. I shouldn't have to give my project a name if I'm just trying to require some dependencies.

**Comment by gerardroche** [comment]
This is a very old issue, was it it ever fixed?

**Comment by eddiemonge** [comment]
doesn't really matter as bower is sort of dead.
