### ISSUE TITLE
"overrides" property proposal

### ISSUE THREAD

**Issue by mnquintana** [bower/spec#38]
After coming across quite a few bower packages without `main` files specified, I was thinking it would be quite useful to have an `overrides` property defined in the bower.json spec. `overrides` would allow package consumers to specify main files of their choosing, overriding the `main`s specified by the packages they're using.

This is already being used in a few build tools / plugins like [main-bower-files](https://github.com/ck86/main-bower-files) and [wiredep](https://github.com/taptapship/wiredep), but it would be better if it were actually part of the official spec.

Some package authors specify multiple redundant `main` files (ie. one minified, one un-minified), and if you're using any kind of build automation that involves bower, having the ability to choose the one that best fits your project in your bower config itself would be a godsend. Everything else I've tried / seen just feels hacky. 

This is even more important for bower packages that don't define a `main` file at all - at that point you have to manually specify which file you want in your code.

My thought is that it would work something like it does here: https://github.com/ck86/main-bower-files#overrides-options

```json
{
    "name": "your-package-name",
    "dependencies": {
        "<bower-package>": "*"
    },
    "overrides": {
        "<bower-package>": {
          "main": "some-file.js"
        }
    }
}
```

Or, `NODE_ENV` specific overrides:
```json
{
    "overrides": {
        "<bower-package>": {
            "main": {
                "development": "file.js",
                "production": "file.min.js",
            }
        }
    }
}
```

`"main"` here would also be able to accept a glob.

What do you think?

**Comment by sheerun** [comment]
As mentioned in #27, it can be now handled by Pluggable Resolver
