### ISSUE TITLE
Proposal for an optional "supportedVersions" property

### ISSUE THREAD

**Issue by josephkaptur** [bower/spec#41]
It’s difficult to get a straight answer on what platforms a given app can support. Consider the following bower.json:

    {
      "name": "example",
      "version": "0.0.1",
      "dependencies": {
        "jquery": "1.9",
        "codemirror": "~4.2.0",
        "seedrandom": "~2.3.10"
      }
    }

To know what platforms this package can support, I’ll need to read a table at http://jquery.com/browser-support/, look towards the bottom of http://codemirror.net/2/, and read between the lines of https://github.com/davidbau/seedrandom/blob/master/README.md. 

I propose an optional “supportedPlatforms” property. Packages could use this as the set of platforms for which they are willing to accept bugs. For example, jQuery 1.9’s could look like this:

    “supportedPlatforms”: [
      “Chrome 38+”,
      “Firefox 32+”,
      “Internet Explorer 6+”,
      …
    ]

This would allow tools to calculate the intersection of the dependency set. For instance, the example above cannot support mobile well (because CodeMirror doesn’t yet). 

I don’t have a good proposal for the exact values of the array. 
* User-Agent string seems too hard to read.
* Arbitrary text doesn’t provide enough standardization to be useful (though it is still much more organized than the current state of the world). 
* As I understand it, semver isn't used by browsers and doesn't define ranges in a standard way. 
* Some type of object could be used: 

    “supportedPlatforms”: [
      {browser: “chrome”, versions: “38-39”}
      …
    ]

This proposal takes inspiration from npm’s “engines”, “engineStrict”, “os”, and “cpu” properties. These use [an extension of semver](https://www.npmjs.org/doc/misc/semver.html). 

This may be too simple. “Supported” is not necessarily a binary state: for instance, a package might support only some features in IE. However, as I see it, “supportedPlatforms” isn’t a replacement for reading documentation, it’s only meant to clarify which platforms are completely out-of-scope. 

Does this seem useful?

**Comment by sheerun** [comment]
There is no point in standardising this field on bower side. It really depends on the tool you use. For example you can write a pluggable resolver that interprets this fields in some way. There are no sensible semantics bower can force on community here, so feel free to invent your own and spread it.

Another good place to put this field is of course package.json
