### ISSUE TITLE
How should local components be specified and consumed to avoid duplication?

### ISSUE THREAD

**Issue by nmalaguti** [bower/spec#45]
I'd like to get some opinions about how to handle developing multiple components in the same repository that all depend on each other. I'd like to use `bower.json` to manage both my **internal** and **external** components so I can keep all dependency ordering information in the same place (for both build order and script order in my html).

For my usage:

- **external** components are components that are not in the same repo/project
  - bower registry version
  - git repo
  - url to archive
- **internal** components are components that are in the same repo/project
  - specified by a relative path

Local paths are already supported in the spec, but their handling is less than ideal.

> Dependencies are specified with a simple hash of package name to a semver compatible identifier or URL.
> 
> * Local paths may be used as values for local development, but they will be disallowed when registering.

The current behavior of bower is that all components, both internal and external, are **copied** into the `bower_components` directory. If you are actively developing on both components, you need to keep re-running `bower install` in order to get the latest code into the dependent components.

Alternative approaches are to:

- use `bower link`
  - this uses global state and makes it hard to keep all required state within a single repo
- use manual symlinks between `bower_components/comp-1` -> `local/path/to/comp-1` and commit them to the repo
  - this doesn't work well on all platforms or with all tools (e.g. globbing) and not all git implementations support symlinks

#### Possible approach

One way to support this would be to add `localDependencies` and `localDevDependencies` properties to `bower.json`.

**internal-example**
```json
{
  "name": "internal-example",
  "dependencies": {
    "angular-ui-router": "~0.2.13"
  },
  "devDependencies": {
    "mocha": "~2.2.1",
    "chai": "~2.2.0"
  },
  "localDependencies": {
    "example-lib": "../example-lib"
  },
  "localDevDependencies": {
    "example-core": "../example-core"
  }
}
```

**example-lib**
```json
{
  "name": "example-lib",
  "dependencies": {
    "moment": "~2.10.3"
  },
  "devDependencies": {
    "mocha": "~2.2.1",
    "chai": "~2.2.0"
  },
  "localDependencies": {
    "example-core": "../example-core"
  }
}
```

**example-core**
```json
{
  "name": "example-core",
  "dependencies": {
    "lodash": "~3.6.0"
  },
  "devDependencies": {
    "chai": "~2.2.0",
    "mocha": "~2.2.1",
    "angular-mocks": "~1.3.15"
  }
}
```

When running `bower install` in `internal-example` (assume `bower install` has already been run for the other components), the following would be the output into `internal-example/bower_components`:
- angular (dependency of angular-ui-router)
- angular-ui-router (dependency of internal-example)
- chai (devDependency of internal-example)
- mocha (devDependency of internal-example)
- **Note: none of the dependencies of the `localDependencies` are included here**

None of the `localDependencies` or `localDevDependencies` (or their `dependencies` like moment) were copied into `bower_components`. However, the version numbers were checked by bower to make sure there were no conflicts.

If `example-lib` and `example-core` have dependencies on incompatible versions of `jquery`, bower should probably just report an error and fail the installation - since these are **internal** components the author should fix incompatibilities in the dependencies rather than in the parent.

**Alternatively, bower should continue to operate as usual by copying in all `dependencies` except `localDependencies`**. My rationale is that if you update your dependencies in a local dependency (e.g. moment from v1.1 to v2.0) you need to make sure to run `bower install` everywhere that local dependency is referenced. The behavior of not copying may introduce too much weirdness or unexpected behavior.

##### Consuming internal components

Tools like wiredep would need to be updated to follow the paths of `localDependencies` and respect any `.bowerrc` files found there in order to find the correct `bower_components` folder.

The output from wiredep for the above project might look like:

```javascript
console.log(JSON.stringify(require('wiredep')({
  dependencies: true,
  devDependencies: false,
  localDependencies: true,
  localDevDependencies: true
}), null, 2));
```

```json
{
  "packages": {
    "angular": {
      "main": [
        "/Users/nmalaguti/git/my-example/internal-example/bower_components/angular/angular.js"
      ],
      "type": [
        ".js"
      ],
      "name": "angular",
      "dependencies": {}
    },
    "angular-ui-router": {
      "main": [
        "/Users/nmalaguti/git/my-example/internal-example/bower_components/angular-ui-router/release/angular-ui-router.js"
      ],
      "type": [
        ".js"
      ],
      "name": "angular-ui-router",
      "dependencies": {
        "angular": ">= 1.0.8"
      }
    },
    "moment": {
      "main": [
        "/Users/nmalaguti/git/my-example/example-lib/bower_components/moment/moment.js"
      ],
      "type": [
        ".js"
      ],
      "name": "moment",
      "dependencies": {}
    },
    "lodash": {
      "main": [
        "/Users/nmalaguti/git/my-example/example-core/bower_components/lodash/lodash.js"
      ],
      "type": [
        ".js"
      ],
      "name": "lodash",
      "dependencies": {}
    },
    "exp-core": {
      "main": [
        "/Users/nmalaguti/git/my-example/example-core/build/src/foo.js"
      ],
      "type": [
        ".js"
      ],
      "name": "example-core",
      "dependencies": {
        "lodash": "~3.6.0"
      }
    },
    "example-lib": {
      "main": [
        "/Users/nmalaguti/git/my-example/example-lib/build/src/styles/inner/deer.css",
        "/Users/nmalaguti/git/my-example/example-lib/build/src/styles/rabbit.css",
        "/Users/nmalaguti/git/my-example/example-lib/build/src/image.css",
        "/Users/nmalaguti/git/my-example/example-lib/build/src/bar.js"
      ],
      "type": [
        ".css",
        ".js"
      ],
      "name": "example-lib",
      "dependencies": {
        "moment": "~2.10.3",
        "example-core": "../example-core"
      }
    }
  },
  "js": [
    "/Users/nmalaguti/git/my-example/internal-example/bower_components/angular/angular.js",
    "/Users/nmalaguti/git/my-example/internal-example/bower_components/angular-ui-router/release/angular-ui-router.js",
    "/Users/nmalaguti/git/my-example/example-lib/bower_components/moment/moment.js",
    "/Users/nmalaguti/git/my-example/example-core/bower_components/lodash/lodash.js",
    "/Users/nmalaguti/git/my-example/example-core/build/src/foo.js",
    "/Users/nmalaguti/git/my-example/example-lib/build/src/bar.js"
  ],
  "css": [
    "/Users/nmalaguti/git/my-example/example-lib/build/src/styles/inner/deer.css",
    "/Users/nmalaguti/git/my-example/example-lib/build/src/styles/rabbit.css",
    "/Users/nmalaguti/git/my-example/example-lib/build/src/image.css"
  ]
}
```

#### Criticism

I'm not sure if this is the right way to use `bower.json` or if this is a goal of `bower.json`. I'm interested in this because it simplifies the dependency ordering story for the build order of components and for including them in html.

**Comment by sheerun** [comment]
You can use local dependencies as so:

```
{
  "dependencies": {
    "some_name": "./path/to/dependency"
  }
}
```
