### ISSUE TITLE
Rename repository to bower-spec and add .bowerrc specificaton

### ISSUE THREAD

**Issue by sheerun** [bower/spec#52]
I think it's important to document both in one place. What do you think @desandro ?

**Comment by desandro** [comment]
I like moving it to one repo. But, this repo was nice as you could read the spec in the README. If we merge both specs into one file, it may be confusing.

**Comment by sheerun** [comment]
We could put both spec with headers and maybe TOC at the top. No need to split to separate documents.

**Comment by benschwarz** [comment]
I think we should rename this repo to `spec` and add `.bowerrc`.

**Comment by sheerun** [comment]
yes

**Comment by sheerun** [comment]
@desandro @benschwarz I've added `.bowerrc` specifiction here. Could you proofread it and commit fixes?  :)
