### ISSUE TITLE
Formatting of Deprecated is Confusing

### ISSUE THREAD

**Issue by wrumsby** [bower/spec#56]
The formatting of Deprecated when describing the `version` property is confusing and suggests that the property _is not_ deprecated. 

![screen shot 2015-10-16 at 3 17 42 pm](https://cloud.githubusercontent.com/assets/83479/10532322/8f26aad0-7419-11e5-82a9-2cfdade72df9.png)

I would recommend changing the formatting to be consistent with other attributes (i.e. italicised, no punctuation).

**Comment by sheerun** [comment]
OK :) Can you send a PR?
