### ISSUE TITLE
example of environment variables seems incorrect

### ISSUE THREAD

**Issue by jaraco** [bower/spec#58]
In the config spec, it states:

```
Example of valid environment variables:

    bower_https_proxy is evaluated as https-proxy
    bower_storage__cache is evaluated as storage.cache
```

But in the description of `storage`, the only valid keys are `packages`, `registry`, and `link` with no mention of `cache`. This confusion example also appears on [the docs](http://bower.io/docs/config/) for config.

Am I right in thinking these examples should be updated to match the valid keys? Am I also right in thinking that one needs to override all three if ~/.bower is not available?

**Comment by ptitgraig** [comment]
Hello.
The doc has been updated with `packages`. You do can override all three:
https://github.com/bower/spec/blob/master/config.md#storage

**Comment by jaraco** [comment]
Thanks!
